-- 空房子室內設計 案例後台資料表 + 既有 15 筆匯入
-- 在 Supabase → SQL Editor 貼上整段執行一次即可。可重複執行（會先清空再匯入）。

create table if not exists cases (
  id          bigint generated always as identity primary key,
  sort_order  int  not null default 0,
  cat         text not null default '住宅設計',
  zh_name     text not null default '',
  en_name     text not null default '',
  tagline     text default '',
  hero        text default '',
  meta        jsonb default '[]'::jsonb,
  story       text default '',
  problem     text default '',
  solution    text default '',
  highlights  jsonb default '[]'::jsonb,
  gallery     jsonb default '[]'::jsonb,
  created_at  timestamptz default now()
);

-- 與專案其他資料表一致：關閉 RLS（用 service role 從 API 讀寫）
alter table cases disable row level security;

-- 匯入既有 15 筆（重跑會先清空，避免重複）
truncate table cases restart identity;
insert into cases
  (sort_order, cat, zh_name, en_name, tagline, hero, meta, story, problem, solution, highlights, gallery)
values
(1, '住宅設計', '墨石', 'Smoke & Stone', '沉穩的質感，是每天回家的踏實', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/smoke-and-stone-hero', '["建案改造","低調奢華","極簡風","台中・沙鹿"]'::jsonb, '位於沙鹿的這個家，屋主要的不是一眼驚豔的華麗，而是一種沉得住、住得久的質感。比起跟風的設計，他更在意每天回到家時，空間能不能讓人安定下來。我們以生活為核心，為他量身打造這個沉穩的家。', '客廳有一道因窗戶位置而來的穿堂風——氣流直穿，坐起來不安定，風水上也是忌諱。同時屋主有不少想展示的收藏，需要既能陳列、又能把雜物收得乾淨俐落的空間。', '以深灰／黑色霧面烤漆、大理石拼接、煙燻玻璃鋪陳出低調而有層次的奢華。客廳櫃體巧妙增生出一道量體，順勢化解穿堂風，風水與生活舒適一次兼顧。機能上分成三區：右側玻璃櫃展示收藏，中段平台可放電視或藝術品，左側收納櫃把物品藏起來。隱藏收納、間接照明、曲面櫃門，每個細節都同時顧到美感與功能。', '["一道量體同時化解穿堂風，風水與生活舒適一起顧到","展示、影音、收納三區分明，收藏有面子、雜物有裡子"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/smoke-and-stone-1","caption":"客廳量體化解穿堂風，落地窗引入採光"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/smoke-and-stone-2","caption":"曲面櫃門與黑色霧面，從玄關就定調"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/smoke-and-stone-3","caption":"多功能空間，胡桃木質帶來溫度"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/smoke-and-stone-4","caption":"木紋檯面與霧面抽屜的細膩銜接"}]'::jsonb),
(2, '住宅設計', '常日', 'Everyday', '家的樣子，是最貼近日常的剛剛好', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/everyday-hero', '["建案整體設計","日式溫潤","梧棲・大毅建案","台中"]'::jsonb, '這是為梧棲大毅建案屋主做的整體設計。屋主要的不是樣品屋式的展示，而是一個貼近日常、住起來剛剛好的家。我們從圖面構思一路陪到現場落地，讓完工那刻的模樣，就是當初想像的樣子。', '建案交屋時像一張白紙，格局、收納、動線都還沒有屬於這個家的答案。如何把屋主的生活習慣準確地裝進這個空間，是整個設計的核心。', '以日式溫潤為基調，用木質、白與柔和的紙燈光線鋪陳全室。從玄關的收納與端景、客廳的中島檯面、臥室的木作衣櫃，到開放與隱藏並存的廚房收納，我們用整體設計串連材質、光線與動線，讓每個區域都剛剛好。家的樣子沒有標準答案，只有最貼近屋主日常的那一種。', '["木質與白的溫潤基調，紙燈柔光貫穿全室","玄關、客廳、廚房、臥室整體設計，動線一氣呵成"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/everyday-1","caption":"開闊的客廳與紙燈柔光，是日常的一隅"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/everyday-2","caption":"臥室木作衣櫃，霧面玻璃拉門透著柔光"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/everyday-3","caption":"白與木的廚房，開放層架點出溫度"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/everyday-4","caption":"衣櫃內部：吊掛與抽屜，收納一目了然"}]'::jsonb),
(3, '住宅設計', '無痕', 'Seamless', '收納與門，都隱進牆面裡', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/seamless-hero', '["大面收納","隱藏門設計","清水","台中"]'::jsonb, '清水這個家，屋主希望空間看起來乾淨、不被櫃子和門切得零碎。生活要用的收納一樣都不能少，但不想讓它們搶走空間的安靜。我們的任務，是把大量的收納藏進牆裡，讓家維持整面的完整與留白。', '原本的格局有外露的柱子與多道門，視覺被切得破碎，收納也不足。如何在不犧牲機能的前提下，讓空間看起來更完整、更寬，是設計的核心。', '我們以隱藏式推門將柱子與牆體融為一體，門關上時就是一整面乾淨的牆，空間不再被切割。微水泥質感的整面收納櫃從玄關延伸到客廳，搭配木質地台與玻璃展示櫃，把生活用品、收藏與雜物分層收好。臥室則用直紋推拉門衣櫃與獨立更衣間，吊掛、層板、抽屜分區明確，收納大、卻不顯重。', '["隱藏式推門讓柱與牆融為一體，關上即是完整的牆面","從玄關到臥室整面收納，機能藏起、留白留下"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/seamless-1","caption":"直紋推拉門衣櫃，光影斜落在櫃面"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/seamless-2","caption":"衣櫃內部：吊掛、層板、抽屜分區明確"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/seamless-3","caption":"獨立更衣間，鏡面與木質放大空間"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/seamless-4","caption":"主臥整面收納，順勢連到後方更衣動線"}]'::jsonb),
(4, '住宅設計', '長案', 'The Long Table', '沙發背後一道長桌，讓客廳能工作也能生活', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/the-long-table-hero', '["客廳複合機能","長桌書桌","調光簾採光","清水・台中"]'::jsonb, '清水這個家坪數不大，屋主不希望客廳只有「看電視」一種用途。他想要一個能工作、能閱讀、能放下樂器、也能和家人一起坐下來的空間。我們把這些日常，收進一道長桌裡。', '不大的客廳如果只擺沙發與電視，機能單一，也浪費了採光最好的位置。如何讓同一個空間身兼客廳、書房與生活角落，是這次設計要解的題。', '我們在沙發背後設置一道吧台高度的木質長桌，它同時是書桌、吧台與工作檯，活化了原本只能放沙發的客廳。搭配弧形長虹玻璃屏風界定餐廚、又讓光線穿透；調光簾濾進的波光灑在桌面與地坪上。以自然材質與低碳綠建築的理念鋪陳，讓這個複合機能的空間，依然溫暖、明亮、自在。', '["沙發背後一道長桌，客廳同時是書房與生活角落","弧形長虹玻璃與調光簾，引光入室、界定不阻斷"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/the-long-table-1","caption":"沙發背後的長桌，是書桌，也是生活的角落"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/the-long-table-2","caption":"長桌延伸，串起客廳、餐廚與收納"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/the-long-table-3","caption":"弧形長虹玻璃屏風，引光也輕輕分界"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/the-long-table-4","caption":"調光簾濾進的光，落在餐桌一隅"}]'::jsonb),
(5, '住宅設計', '留白', 'Negative Space', '極簡不是少，是留白裡的呼吸與溫度', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/negative-space-hero', '["極簡留白","減法生活","北屯・台中"]'::jsonb, '北屯的這個家，屋主想要的很簡單——一個回來能卸下疲憊、讓心安靜下來的地方。不要過多的裝飾與色彩，只要乾淨、溫潤、能好好呼吸的空間。', '極簡最難的，是「少」之後還要有溫度，不能變得冷清空洞。如何在大量留白裡，仍讓人感到安心、被包覆，是設計要拿捏的分寸。', '我們以留白為主軸，用米白、灰藍與木質鋪陳層次，把收納整合進一整面白色櫃體、藏起雜物，只留下乾淨的牆面與光。低台度的電視櫃、灰藍主牆、純白紗簾濾進的日光，再加上一盞玻璃吊燈的暖光，讓減法的空間依然有溫度。回到這裡，生活自然慢下來。', '["大量留白裡用木質與暖光留住溫度，簡而不冷","整面白色收納藏起雜物，只留乾淨的牆與光"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/negative-space-1","caption":"米色皮沙發面向陽台，紗簾濾入柔光"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/negative-space-2","caption":"餐廳整面白色收納，留一格放對講機與隨手小物"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/negative-space-3","caption":"大理石餐桌與玻璃吊燈，是留白中的一點溫度"}]'::jsonb),
(6, '住宅設計', '木格', 'Lattice', '讓視線延伸，空間簡約而舒緩', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/lattice-hero', '["簡約大方","格柵電視牆","日式無印","台中"]'::jsonb, '屋主想要的是一個簡單、開闊、能放鬆的家——不被多餘的裝飾與雜物佔據，讓視線和心情都能慢慢延展開來。我們以簡約大方為方向，把空間的線條拉長、把感受放鬆。', '空間最怕被切得零碎、被櫃子和雜物塞滿，視覺一卡住就顯得擁擠。如何讓視線一路延伸、空間感被拉長，同時保有溫度，是這次的設計重點。', '我們把收納整合進一整面系統櫃、收得乾淨俐落，讓牆面平整、視線一路延伸不被打斷，空間感自然被拉長。客廳以木格柵電視牆搭配石材，做出沉穩的視覺重心；廚房用黑框玻璃隔間，區隔油煙又保留通透與採光。木質與暖光鋪陳全室，讓開闊的空間依然溫潤、舒緩。', '["整面系統櫃收得乾淨平整，讓視線延伸、空間被拉長","木格柵電視牆與石材，為開闊空間定下沉穩重心"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/lattice-1","caption":"暖光下的客餐廳，紅白吊燈點出生活感"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/lattice-2","caption":"黑框玻璃隔間廚房，擋油煙也保留通透"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/lattice-3","caption":"從玄關延伸的整面系統櫃，收納藏於牆面"}]'::jsonb),
(7, '住宅設計', '摩卡', 'Mocha', '摩卡色的溫暖，讓家成為最安定的所在', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/mocha-hero', '["摩卡色系","簡約風","黑框玻璃廚房","台中"]'::jsonb, '屋主希望一進門就能感到安定、放鬆——不是冷調的極簡，而是帶著溫度、讓人想久待的家。我們從色彩出發，為這個家定下摩卡色的基調。', '全室如果用太冷的灰白，會顯得理性卻少了暖意；但暖色用過頭又容易顯舊。如何用一個顏色把「溫暖」與「高級感」同時做到，是這次的關鍵。', '我們以摩卡色作為全室主調——溫潤的大地色系帶來安心與穩定，也是近年精品與高級住宅偏愛的質感色。從電視牆、整面系統櫃到餐邊櫃都統一在這個色階裡，再用黑框玻璃隔間界定餐廚、以玻璃展示櫃與間接照明提亮層次。色彩、格局與光線一起，讓家成為讓人放鬆、充滿暖意的所在。', '["以摩卡大地色統一全室，溫暖又帶精品質感","黑框玻璃隔間與展示櫃，劃分餐廚也保留通透"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/mocha-1","caption":"黑框玻璃隔間界定餐廚，霧鏡吊燈點出層次"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/mocha-2","caption":"摩卡色餐邊櫃，鏡面背牆放大空間"}]'::jsonb),
(8, '住宅設計', '曜', 'Onyx', '黑白灰之間，低調而優雅的輕奢', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/onyx-hero', '["現代風","黑白灰輕奢","大理石","台中"]'::jsonb, '屋主嚮往的是一種低調卻有份量的居家——不喧嘩、不繁複，但每個細節都看得到質感。我們以黑、白、灰為主調，為這個家定下現代輕奢的語彙。', '輕奢最怕流於浮誇。如何用最克制的黑白灰，做出層次與高級感，而不是一味堆砌昂貴材質，是這次設計的關鍵。', '我們以簡潔的線條收齊空間，用黑框玻璃展示櫃、大理石與花崗岩中島堆疊出層次；深色木質電視牆沉穩內斂，間接照明把材質的紋理輕輕托出。不張揚，卻處處是質感——在低調之中展現優雅，於簡約之內藏著個性。', '["以黑白灰與細緻建材堆疊層次，輕奢而不浮誇","黑框玻璃展示櫃與石材中島，低調中見份量"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/onyx-1","caption":"餐廚與黑玻展示櫃相鄰，白色廚房在後通透延伸"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/onyx-2","caption":"深色木質電視牆，沉穩內斂的視覺重心"}]'::jsonb),
(9, '住宅設計', '悠流', 'Flow', '開放通透，讓光與生活自在流動', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/flow-hero', '["北歐無印","開放式設計","大書牆","台中"]'::jsonb, '屋主想要一個開放、通透、住起來輕盈自在的家——不要太多隔間把空間切死，讓光線和家人的動線都能自由流動。我們在設計階段就用 3D 圖把這份「流動感」模擬到位，再一比一落地。', '原本的隔間讓公共區顯得零碎、採光也被擋住。如何打開格局、讓客廳、餐廳到後方一氣呵成，同時保留足夠的收納，是這次設計的核心。', '我們以開放式布局打開公共區，客廳、餐廳與廚房之間不做滿牆，讓視線與光影一路流轉、空間更顯通透輕盈。一整面格子書牆兼顧收納與展示，木質家具與灰綠牆面帶來北歐的溫潤；成排吊燈界定餐桌、卻不阻斷視線。家，於是有了呼吸的節奏。', '["開放式布局打開公共區，光與動線自在流動","整面格子書牆，收納與展示一次到位"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/flow-1","caption":"米色沙發與木質家具，客廳溫潤放鬆"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/flow-2","caption":"餐廳串連客廳與廚房，動線開放流暢"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/flow-3","caption":"整面格子書牆，收納與展示一次到位"}]'::jsonb),
(10, '住宅設計', '歇', 'Repose', '奶茶色裡，把臥室留給安靜的休息', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/repose-hero', '["奶茶色","侘寂簡約","主臥設計","台中"]'::jsonb, '延續公共區的奶茶色調，臥室要的是更純粹的安靜——一個下班後能徹底放鬆、好好休息的角落。我們把機能收進牆面，讓睡眠的空間回到最單純的樣子。', '臥室坪數有限，又要塞進衣櫃、書桌、床頭收納。如何在不犧牲收納的前提下，維持視覺的乾淨與放鬆感，是設計的重點。', '以奶茶與米灰鋪陳柔和的底色，床頭整合收納層板、轉角結合衣櫃與書桌，把機能藏進簡潔的線條裡。深色懸浮層板與黑陶擺件，為一室的溫柔加上一點重量，帶出侘寂的安靜質感。', '["床頭、衣櫃、書桌整合進牆面，機能藏於簡潔","奶茶色搭深色擺件，柔和中見侘寂的沉靜"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/repose-1","caption":"床頭收納整合層板，黑色擺件點出侘寂感"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/repose-2","caption":"轉角結合衣櫃與書桌，機能藏在簡潔線條裡"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/repose-3","caption":"頂天衣櫃與抽屜，收納量足卻不顯壓迫"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/repose-4","caption":"深色層板與黑陶擺件，奶茶色裡的一點重量"}]'::jsonb),
(11, '住宅設計', '光格', 'Lightframe', '光影落在層架之間，鋪出溫柔的日常', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/lightframe-hero', '["現代簡約","灰階木質","發光展示層架","豐原・台中"]'::jsonb, '為豐原的屋主打造的家，是一份屬於未來的生活提案。屋主重視細節與質感，希望空間不只是好看，更能在每天的光影流轉裡，慢慢長出屬於自己的溫度。', '現代風格容易做得冷硬。如何用灰階與俐落線條撐起現代感，又透過木質與光影留住生活的溫柔，是這個家要拿捏的平衡。', '我們從光影配置與材質紋理著手：以灰階為基調，搭配木質餐桌、黑大理石量體與發光的開放層架，讓現代俐落裡有層次也有溫度。黑框玻璃拉門界定書房與公共區、又保留通透。每一處細節，都是為這位屋主量身鋪陳的日常想像。', '["灰階線條搭木質與發光層架，現代俐落而不冷硬","黑框玻璃拉門界定書房，通透又獨立"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/lightframe-1","caption":"發光開放層架界定客餐廳，材質紋理在光影中浮現"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/lightframe-2","caption":"多功能室以整面層板與收納，留白而有餘裕"}]'::jsonb),
(12, '住宅設計', '新生', 'Renewal', '老屋翻新，讓每一間都重新被好好生活', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/renewal-hero', '["老屋翻新","套房規劃","北歐簡約","康樂街・台中"]'::jsonb, '康樂街的這棟老屋，要翻新成一間間能獨立生活的套房。屋主希望每一間雖然坪數不大，卻都能採光明亮、機能完整，讓租客一住進來，就覺得這裡是個能好好生活的家。', '老屋格局零碎，採光與管線都是挑戰。如何在有限坪數裡，把睡眠、收納、迷你廚房與獨立衛浴通通安排妥當，又不顯擁擠，是這次翻新的關鍵。', '我們以北歐簡約為基調，灰木地板搭配白牆與黑框窗，讓每間套房都明亮通透。頂天衣櫃結合開放層板、床尾整合書桌、轉角配置迷你廚房與獨立衛浴，把機能塞得剛剛好。弧形天花與間接照明則為小空間添了一分柔和，住起來舒服，也好出租。', '["小坪數塞進睡眠、收納、廚房、衛浴，機能完整不擁擠","灰木地板＋白牆＋黑框窗，每間都明亮好整理"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/renewal-1","caption":"整面採光配書桌與迷你廚房，一個人住明亮舒適"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/renewal-2","caption":"頂天衣櫃結合開放層板，小坪數也有充足收納"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/renewal-3","caption":"床尾結合書桌與滑門衣櫃，動線俐落不佔空間"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/renewal-4","caption":"迷你廚房、衣櫃、衛浴一應俱全，一個人住剛剛好"}]'::jsonb),
(13, '住宅設計', '恰好', 'Just Right', '不多不少，剛好是你想要的生活', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/just-right-hero', '["現代輕奢","微水泥・木質","大理石電視牆","太平・台中"]'::jsonb, '太平的這間新成屋，屋主想要的不是華麗的堆疊，而是一種「恰恰好」的舒服——現代、有質感，卻又能讓人徹底放鬆。就像案名說的，櫻花開得恰恰好，生活也該如此。', '新成屋的格局方正，但白牆與制式建材少了點個性。如何在不大動格局的前提下，用材質與光線堆出層次與溫度，讓每個空間都有記憶點，是設計的方向。', '公共區以大理石電視牆與木質懸浮櫃體拉出大器的第一眼，弧形木格柵展示櫃則柔化線條。臥室改用微水泥牆搭木皮與深色系統櫃，嵌入燈帶讓光暈包覆睡眠區，沉穩而溫暖。多功能房以架高地板整合書桌與收納，把坪效拉到最滿。現代輕奢的底子裡，藏的是剛剛好的生活溫度。', '["大理石電視牆＋弧形木格柵櫃，公共區大器又柔和","臥室微水泥嵌燈帶，光暈包覆出沉穩睡眠氛圍"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/just-right-1","caption":"大理石電視牆鋪滿整面，搭木質懸浮櫃體俐落大器"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/just-right-2","caption":"主臥以微水泥、木皮與深色衣櫃，鋪出沉穩的暖度"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/just-right-3","caption":"床頭微水泥牆嵌燈帶，柔和光暈包覆睡眠區"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/just-right-4","caption":"架高地板結合書桌與收納，多功能房一坪都不浪費"}]'::jsonb),
(14, '住宅設計', '預見', 'Preview', '在動工之前，先看見家的樣子', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/preview-hero', '["3D 設計渲染","現代簡約","奶茶色・微水泥","台中"]'::jsonb, '還沒動工，就想先看見家完成後的樣子嗎？這個案子，我們用 3D 擬真渲染把設計提案一比一呈現出來——從家具配置到燈光氛圍，讓屋主在施工前就能身歷其境地確認每個細節。', '平面圖很難想像實際住起來的感覺。色彩、材質、光線與家具比例，光看 2D 圖容易有落差，等做出來才發現不對，往往為時已晚。', '我們以奶茶色與微水泥鋪陳溫潤的現代簡約：微水泥電視牆搭木地板、開放式餐廚整合電器收納櫃、灰布沙發配圓几與球形吊燈。透過 3D 渲染，這些細節在動工前就能反覆討論、修正到滿意，把「做出來不如預期」的風險降到最低。', '["3D 擬真渲染，動工前先確認材質、光線與家具配置","奶茶色＋微水泥的現代簡約，溫潤而耐看"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/preview-1","caption":"灰布沙發面向採光，客廳留出開闊的活動尺度"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/preview-2","caption":"微水泥電視牆搭懸浮木質櫃，溫潤又俐落"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/preview-3","caption":"開放式餐廚整合電器收納，圓桌串起餐廳與廚房"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/preview-4","caption":"電器收納櫃內嵌咖啡機與微波爐，機能藏得剛好"}]'::jsonb),
(15, '商業空間', '酵境', 'Catalyst', '把酵素科學，變成走得進去的空間', 'https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/catalyst-hero', '["商業空間","餐飲店舖","壹偲 OnlyEase","新竹竹科"]'::jsonb, '壹偲 OnlyEase 是主打無加糖酵素保健的手搖飲品牌，從台中起家，這次要在新竹竹科開第二家店。品牌想說的不是「又一家手搖飲」，而是「喝的保養品」——所以空間要讓人一走進來，就感覺到專業、乾淨，跟健康有關。', '手搖飲在多數人印象裡熱鬧、平價、同質性高。但壹偲的定位是保健酵素，訴求與客單都更高；若照一般手搖店的視覺去做，反而會稀釋品牌的專業感與信任。', '我們把「酵素科學」直接變成空間語言。以黃白品牌色為基調，六角分子幾何貫穿取餐窗、嵌入層架，並做成一整面酵素分子結構壓花牆；檯面與桌腳採不鏽鋼，飲品以錐形瓶、量杯盛裝，把實驗室的乾淨與精密帶進日常。深灰主牆襯托品牌主張 Refresh, Revive, Rejoice，讓每位走進來的人，先感覺到「這是喝的保養品」。', '["六角分子幾何貫穿全店，把酵素科學變成可感知的空間語言","黃白品牌色＋不鏽鋼實驗室質感，建立保健飲品的專業信任感"]'::jsonb, '[{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/catalyst-1","caption":"圓柱展示台以不鏽鋼飾帶收邊，搭配六角壁龕陳列 001 ENZYME 酵素產品，延續分子與實驗室語彙"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/catalyst-2","caption":"整面酵素分子結構壓花牆，把化學式變成低調的藝術"},{"src":"https://res.cloudinary.com/dfvmjmwb7/image/upload/kfz-images/catalyst-3","caption":"錐形瓶、量杯盛裝飲品，延續實驗室的精密與乾淨"}]'::jsonb),
(16, '商業空間', '同齊咖吡 西區精忠店', 'Tongqi West District', '一杯咖啡，連結深夜裡的每一次對話', '/images/home/portfolio/home-portfolio-01.jpg', '["商業空間","餐飲店舖","同齊咖啡","台中・西區"]'::jsonb, '同齊咖啡從花蓮起家，主打自家烘焙的精品咖啡與不限時的寧靜空間。西區精忠店落腳台中市西區精忠街，是品牌深入市區巷弄的據點。屋主希望這裡不只是喝咖啡的地方，而是讓人放慢腳步、能夠久坐工作、也能與朋友自在對話的交匯點。', '店面位於住宅巷弄，臨街面有限，要在不大的坪數裡同時容納吧檯作業、自烘豆陳列、單人工作座與多人聚會區，動線容易打結；又要兼顧不限時久坐的舒適與深夜時段的氛圍，照明與材質都得拿捏得剛剛好。', '以咖啡色與奶油白為基調，胡桃木質檯面搭配溫潤間接照明，讓空間在白天明亮、入夜後沉靜。吧檯前移整合自烘豆展示牆，讓沖煮與選豆成為一進門就感受得到的主角；座區分為靠窗單人長桌與內側聚會區，動線各自獨立、互不干擾。可彈性調整的桌椅同時支援場地租賃，讓商務洽公、讀書會與小型聚會都有合適的角落。', '["吧檯與自烘豆展示牆整合，讓選豆與沖煮成為空間的主角","單人長桌與聚會區動線分流，久坐、洽公、聚會各得其所"]'::jsonb, '[{"src":"/images/home/portfolio/home-portfolio-01.jpg","caption":"胡桃木質檯面與間接照明，鋪陳不限時久坐的溫潤氛圍"}]'::jsonb);
